// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlVJ9p2fBDhhqtJW4RdMmm-RtmRaFxgY',
    appId: '1:1005652515792:web:5f91ee7ea9062789ad77d5',
    messagingSenderId: '1005652515792',
    projectId: 'pruebabd-7538a',
    authDomain: 'pruebabd-7538a.firebaseapp.com',
    databaseURL: 'https://pruebabd-7538a-default-rtdb.firebaseio.com',
    storageBucket: 'pruebabd-7538a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpeJP9YbKuCKU2YQBBFU2pdElDP7PuT8E',
    appId: '1:1005652515792:android:0f794acef4bdb960ad77d5',
    messagingSenderId: '1005652515792',
    projectId: 'pruebabd-7538a',
    databaseURL: 'https://pruebabd-7538a-default-rtdb.firebaseio.com',
    storageBucket: 'pruebabd-7538a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3cHvykQm7Kf4oObXkOcej4Vi1X26BkI',
    appId: '1:1005652515792:ios:dc19ef4388cca4b6ad77d5',
    messagingSenderId: '1005652515792',
    projectId: 'pruebabd-7538a',
    databaseURL: 'https://pruebabd-7538a-default-rtdb.firebaseio.com',
    storageBucket: 'pruebabd-7538a.appspot.com',
    iosClientId:
        '1005652515792-ospubvg1kr7tvq5cu1vc1321tv9deqem.apps.googleusercontent.com',
    iosBundleId: 'com.example.motaApp',
  );
}
